config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists do
  	resources :albums do
  		resources :songs
  	end
  end

end

app/models/album.rb
class Album < ApplicationRecord
	has_many :songs
	belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
  end

  def new
  	puts "*"*100
  	@album = Album.new
  end

  def create
    puts "*"*100
    puts album_params
  	@album = Album.new(album_params)
  	if @album.save
  		redirect_to artist_path
  	else
  		render "new"
  	end
  end

  def destroy
  end

  def album_params
  	params.require(:album).permit(:name, :image_url, :released_at)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
   def index
  	@artist = Artist.all
  end

  def new
  	@artist = Artist.new
  end

  def create
  	@artist = Artist.new(artist_params)
  	if @artist.save
  		redirect_to artists_path
  	else
  		render "new"
  	end
  end

  def show
  	@artist = Artist.find(params[:id])
  end

  def destroy
  	@artist = Artist.find(params[:id])
  	@artist.destroy
  	redirect_to artists_path
  end
  private

  def artist_params
  	params.require(:artist).permit(:name, :image_url)
  end 
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

app/views/albums/index.html.erb
<h1>Albums#index</h1>
<p>Find me in app/views/albums/index.html.erb</p>

app/views/albums/new.html.erb
<div class ="container artist">
	<div class= "row">
		<div class="col-sm-12">
			<header>
				<h1> Album nuevo:</h1>
			</header>
			<div class="artist-list">
					<div class = "room">
						<div class= "row">
							<div class="col-sm-7 col-md-8">
								<%= form_for @album, url: artist_albums_path, html: { method: :post } do |f| %>
									<h4>Nombre:</h4>
									<dir class = "form-group">
										<%= f.text_field :name, class: 'form-control input-lg'%>
									</dir>	
									<h4>Imagen:</h4>
									<dir class = "form-group">
										<%= f.text_field :image_url, class: 'form-control input-lg'%>
									</dir>
									<h4>Dia de lanzamiento:</h4>
									<dir class = "form-group">
										<%= f.date_field :released_at, class: 'form-control input-lg'%>
									</dir>		
									<div class="actions text-right">
										<%= f.submit @album.new_record? ? "Crear artista ": "Editar artista", class: "btn btn-primary btn-lg btn-block" %>
									</div>
								<% end %>
							</div>
						</div>
					</div>					
			</div>
		</div>
	</div>
</div>

app/views/artists/_form.html.erb
<div class ="container artist">
	<div class= "row">
		<div class="col-sm-12">
			<header>
				<h1> Artistas nuevos:</h1>
			</header>
			<div class="artist-list">

					<div class = "room">
						<div class= "row">
							<div class="col-sm-7 col-md-8">
								<%= form_for @artist do |f| %>
									<h4>Nombre:</h4>
									<dir class = "form-group">
										<%= f.text_field :name, class: 'form-control input-lg'%>
									</dir>	
									<h4>Imagen:</h4>
									<dir class = "form-group">
										<%= f.text_field :image_url, class: 'form-control input-lg'%>
									</dir>	
									<div class="actions text-right">
										<%= f.submit @artist.new_record? ? "Crear artista ": "Editar artista", class: "btn btn-primary btn-lg btn-block" %>
									</div>
								<% end %>
							</div>

						</div>
					</div>					
			</div>
		</div>
	</div>
</div>

app/views/artists/index.html.erb
<div class ="container artist">
	<div class= "row">
		<div class="col-sm-12">
			<header>
				<h1> Artistas</h1>
				<%= link_to 'Artistas', new_artist_path %>

			</header>
			<div class="artist-list">
				<% @artist.each do |artist| %>
					<div class = "artist-item">
						<img src = "<%= artist.image_url %>">
						<h4><%= artist.name %></h4>	
						<%= link_to 'Borrar de tu lista', artist,method: :delete %>	
						<%= link_to 'Ver albums', artist%>		
					</div>
				<% end %>				
			</div>
		</div>
	</div>
</div>

app/views/artists/new.html.erb
<%= render 'form' %>

app/views/artists/show.html.erb
<div class ="container artist">
	<div class= "row">
		<div class="col-sm-12">
			<header>
				<h1> <%= @artist.name %></h1>
				<img src = "<%= @artist.image_url %>"></br>
				<%= link_to 'Artistas', artists_path %>
				<%= link_to 'Añadir album', new_artist_album_path(@artist.id) %>

			</header>
			<div class="album-list">
				<% @artist.albums.each do |album| %>
					<div class = "album-item">
						<img src = "<%= album.image_url %>", alt="album">
						<h4><%= album.name %></h4>
						<h4><%= album.released_at %></h4>	
						<%= link_to 'Borrar de tu lista', artist_album_path(@artist.id),method: :delete %>	
								
					</div>
				<% end %>				
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotifie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>